from enum import Enum, auto

class TokenType(Enum):
    LEFT_BRACE = auto()
    RIGHT_BRACE = auto()
    LEFT_PAREN = auto()
    RIGHT_PAREN = auto()
    SEMICOLON = auto()
    INT = auto()
    RETURN = auto()
    IDENTIFIER = auto()
    NUMBER = auto()
    WHITESPACE = auto()
    EOF = auto()
    MINUS = auto()
    BITWISE_COMPLEMENT = auto()
    LOGICAL_NEGATION = auto()
    PLUS = auto()
    STAR = auto()
    SLASH = auto()
    AND = auto()
    OR = auto()
    EQUAL = auto()
    NOT_EQUAL = auto()
    LESS_THAN = auto()
    LESS_THAN_OR_EQUAL = auto()
    GREATER_THAN = auto()
    GREATER_THAN_OR_EQUAL = auto()
